stages:
  - test
  - build

default:
  image: ubuntu:24.04
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake ninja-build git

unit_tests:
  stage: test
  script:
    - ./scripts/test.sh build-gitlab-tests

gui_build:
  stage: build
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake ninja-build git qt6-base-dev qt6-multimedia-dev
  script:
    - ./scripts/build.sh build-gitlab-gui

