image: ubuntu:24.04
stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -y -qq cmake g++ make valgrind libgtest-dev python3

build:
  stage: build
  script:
    - bash ./scripts/ensure_test_lib.sh
    - cmake -S . -B build
    - cmake --build build --target tests
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  allow_failure: false

test:
  stage: test
  needs:
    - job: build
      artifacts: true
  script:
    - ls -lah build/bin
    - ./build/bin/tests
  allow_failure: false
